# Generated by Django 5.2.7 on 2025-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('L', '❤️'), ('D', '👎'), ('W', '😮'), ('S', '😢'), ('A', '😡')], max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Creation Date'),
        ),
    ]
