# Generated by Django 5.2.7 on 2025-10-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reaction_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='code',
        ),
    ]
