# Generated by Django 5.2.7 on 2025-10-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_reaction_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
