# Generated by Django 5.2.7 on 2025-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_delete_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('dislike', '👎 Dislike'), ('wow', '😮 Wow'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('laugh', '😂 Laugh'), ('confused', '😕 Confused'), ('celebrate', '🎉 Celebrate'), ('heart', '💖 Heart'), ('star', '⭐ Star'), ('fire', '🔥 Fire'), ('clap', '👏 Clap'), ('pray', '🙏 Pray'), ('muscle', '💪 Muscle'), ('rocket', '🚀 Rocket'), ('100', '💯 100'), ('check', '✅ Check'), ('cross', '❌ Cross'), ('question', '❓ Question'), ('exclamation', '❗ Exclamation'), ('thumbs_up', '👍 Thumbs Up'), ('thumbs_down', '👎 Thumbs Down')], db_index=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
