# Generated by Django 5.2.7 on 2025-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='code',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('dislike', '👎'), ('100', '💯'), ('wow', '😮'), ('sad', '😢'), ('star', '⭐'), ('fire', '🔥'), ('clap', '👏'), ('pray', '🙏'), ('angry', '😡'), ('laugh', '😂'), ('heart', '💖'), ('check', '✅'), ('cross', '❌'), ('muscle', '💪'), ('rocket', '🚀'), ('confused', '😕'), ('question', '❓'), ('celebrate', '🎉'), ('thumbs_up', '👍'), ('exclamation', '❗'), ('thumbs_down', '👎')], db_index=True, max_length=16, unique=True),
        ),
    ]
