# Generated by Django 5.2.7 on 2025-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_reaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reactions',
            field=models.ManyToManyField(to='main_app.reaction'),
        ),
    ]
