# Generated by Django 5.2.7 on 2025-10-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_note_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checklist_created', 'Checklist Created'), ('checklist_deleted', 'Checklist Deleted'), ('reaction_added', 'Reaction Added'), ('reaction_removed', 'Reaction Removed')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.note')),
            ],
        ),
    ]
