# Generated by Django 5.2.7 on 2025-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
