# Generated by Django 5.2.7 on 2025-10-20 21:36

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
