# Generated by Django 5.2.7 on 2025-10-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_category_color_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
